import type { Metadata } from "next";
import "@app/globals.css";
import Link from "next/link";
import Provider from "@app/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="flex h-[80px] w-full min-w-[500px] flex-row items-center justify-around bg-green-300 text-[25px] font-bold">
          <Link href={"/"}>홈</Link>
          <Link href={"/champions"}>챔피언 목록</Link>
          <Link href={"/items"}>아이템 목록</Link>
          <Link href={"/rotation"}>챔피언 로테이션</Link>
        </header>
        <main className="w-full">
          <Provider>{children}</Provider>
        </main>
      </body>
    </html>
  );
}
